# This is for prepare perform maven cmd env
FROM maven:3.5.2-jdk-8 AS build-env
WORKDIR /app
COPY . /app
RUN mvn install

# To provide aks build image
FROM openjdk:8-jdk-alpine
VOLUME ./tmp
COPY --from=build-env /app/payment/target/payment-ms-0.0.1-SNAPSHOT.jar ./app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./app.jar"]
