version: '3'
services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    ports:
      - "8080:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888

  zoo2:
    image: zookeeper
    hostname: zoo2
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888
